### ISSUE TITLE
Implement annotated file.

### ISSUE THREAD

**Issue by krinkin** [OSLL/edu-git-stats#6]
<num changes> string

num_chandes doesn't take string moving in account

**Comment by LDVSOFT** [comment]
Currently thinking of parsing `git log`'s changes. We need to differ:
- Adding of new strings
- Deleting of old ones
- Changes

The way to do it in `--word diff mode` is:
- If all line is `{+...+}` - it's addition
- If all line is `[-...-]` - it's a deletion
- Else - count changes
  The problem are whitespaces lines - in `-w` mode they are empty, hard to understand, are they deleted or added.

Currently thinking of using python's regexps.

**Comment by LDVSOFT** [comment]
Ha.

We can go syncrhonly on 2 `log`s: with `--word-diff` and without one. Then we`ll know from the first our current position in the second one.

**Comment by LDVSOFT** [comment]
Now code can split `log` to blocks of changes. Need to process single block of changes.

We have line from `word_diff`. We also have traced it in casual diff (called `full_diff`)
- If it is not empty:
  - If it is only addition or deletion, we should process that addition/deletion
  - Else it is change. Process it
- Then this is space string. To understand, how it was changed, we look at `full_diff`. It can be seen only in at least one of it's parts:
  - Addition: it' addition
  - Deletion: it's deletion
  - Both: 0-change, do nothing

**Comment by LDVSOFT** [comment]
Oh, it's actually needed to look up `full_diff` for every - even non empty - line, took a huge time to realize.
